# Generated by Django 3.1.5 on 2021-03-11 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountHolder', models.CharField(max_length=25)),
                ('AccountNumber', models.BigIntegerField()),
                ('MobileNumber', models.BigIntegerField()),
                ('Address', models.TextField()),
                ('IssueType', models.CharField(max_length=8)),
                ('Issue', models.TextField()),
                ('PostalZip', models.CharField(max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ContactUs',
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.BigIntegerField()),
                ('Name', models.CharField(max_length=25)),
                ('TransactionID', models.CharField(max_length=12)),
                ('TransactionAmount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
