# Generated by Django 3.1.5 on 2021-03-10 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('mobileNo', models.BigIntegerField()),
                ('homeAddress', models.TextField()),
                ('accountNo', models.BigIntegerField(unique=True)),
                ('AadharNo', models.BigIntegerField(unique=True)),
                ('IFSC_code', models.CharField(default='ABC1234', max_length=7)),
                ('accBalance', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
