# Generated by Django 3.1.5 on 2021-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobileNo', models.BigIntegerField()),
                ('emailAddress', models.EmailField(max_length=254)),
                ('homeAddress', models.TextField()),
                ('accountNo', models.BigIntegerField(unique=True)),
                ('AadharNo', models.BigIntegerField(unique=True)),
                ('IFSC_code', models.CharField(default='ABC1234', max_length=7)),
                ('accBalance', models.BigIntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=14, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
