# Generated by Django 3.1.5 on 2021-03-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='date',
            new_name='BirthDate',
        ),
    ]
