# Generated by Django 3.1.5 on 2021-03-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_master',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20)),
                ('book_price', models.IntegerField()),
            ],
        ),
    ]
